version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: "wednesday"
      time: "10:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    reviewers:
      - "cuenca-mx/admin"
